apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: z1q25v22k-go 
  janus-idp.io/tekton: z1q25v22k-go
  backstage.io/kubernetes-id: z1q25v22k-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: z1q25v22k-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml